version: "3"

services:

  backend:
    build: ./
    ports:
      - 8000:8000

    command: sh -c "python manage.py migrate && python manage.py loaddata initial_users.json && python manage.py loaddata initial_data.json && gunicorn arbicoin.wsgi:application --bind 0.0.0.0:8000 & celery -A arbicoin.celery worker --loglevel=info"

    volumes:
      - static_volume:/app/backend/staticfiles
    env_file:
      - .backend.env
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=arbicoin
      - POSTGRES_PASSWORD=arbicoin_password
      - POSTGRES_DB=pgdbp

  nginx:
    build:
      context: ../arbicoin-frontend
      args:
        API_URL: http://localhost:8000/
    ports:
      - 3000:80
    depends_on:
      - backend

  
  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
  static_volume:
