# Generated by Django 4.0.6 on 2022-08-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100)),
                ('merkle_hash', models.CharField(max_length=100)),
                ('prev_blk_hash', models.CharField(max_length=100)),
                ('unix_timestamp', models.IntegerField()),
                ('height', models.IntegerField()),
                ('num_transactions', models.IntegerField()),
                ('hash_target_zeros', models.IntegerField()),
                ('nonce', models.TextField()),
            ],
        ),
    ]
