# Generated by Django 4.0.6 on 2022-08-05 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='prev_blk_hash',
        ),
        migrations.AddField(
            model_name='block',
            name='prev_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blocks.block'),
        ),
        migrations.AlterField(
            model_name='block',
            name='unix_timestamp',
            field=models.DateTimeField(),
        ),
    ]
