# Generated by Django 4.0.6 on 2022-08-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_alter_block_hash_alter_block_hash_target_zeros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='hash_target_zeros',
            field=models.PositiveIntegerField(default=0, help_text='difficulty of mining the block'),
        ),
    ]
