# Generated by Django 4.0.6 on 2022-08-12 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, help_text='hash of the transaction for identification', max_length=40, null=True)),
                ('tx_inputs_count', models.PositiveIntegerField(blank=True, default=0, help_text='number of inputs in the transaction')),
                ('tx_outputs_count', models.PositiveIntegerField(blank=True, default=0, help_text='number of outputs in the transaction')),
                ('mined', models.BooleanField(default=False, help_text='has the transaction been mined')),
                ('block', models.ForeignKey(blank=True, help_text='block this transaction is part of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blocks.block')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, help_text='hash of the transaction component', max_length=40, null=True)),
                ('value', models.PositiveIntegerField(default=0, help_text='value of the component i.e how much is it worth')),
                ('own_addr', models.CharField(help_text='owner of this component', max_length=100)),
                ('gen_transaction_index', models.PositiveIntegerField(blank=True, help_text='output index in generating transaction', null=True)),
                ('blk_height', models.PositiveIntegerField(blank=True, help_text='height of the block', null=True)),
                ('gen_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, help_text='hash of the transaction component', max_length=40, null=True)),
                ('value', models.PositiveIntegerField(default=0, help_text='value of the component i.e how much is it worth')),
                ('own_addr', models.CharField(help_text='owner of this component', max_length=100)),
                ('gen_transaction_index', models.PositiveIntegerField(blank=True, help_text='output index in generating transaction', null=True)),
                ('spend_transaction_index', models.PositiveIntegerField(default=0, help_text='input index in spending transaction')),
                ('signature', models.TextField(help_text='digital signature for verification')),
                ('gen_transaction', models.ForeignKey(blank=True, help_text='transaction that generated this input', null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
                ('spend_transaction', models.ForeignKey(blank=True, help_text='transcation that spent this input', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
