# Generated by Django 4.0.6 on 2022-08-03 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100)),
                ('tx_ins_ct', models.IntegerField(blank=True, default=0)),
                ('tx_outs_ct', models.IntegerField(blank=True, default=0)),
                ('mined', models.BooleanField(default=False)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='blocks.block')),
            ],
        ),
        migrations.CreateModel(
            name='TxOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('own_addr', models.CharField(max_length=100)),
                ('gen_tx_idx', models.IntegerField()),
                ('blk_height', models.IntegerField(null=True)),
                ('gen_tx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='outputs', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TxIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('own_addr', models.CharField(max_length=100)),
                ('gen_tx_idx', models.IntegerField()),
                ('spend_tx_idx', models.IntegerField(default=0)),
                ('signature', models.TextField()),
                ('gen_tx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='transactions.transaction')),
                ('spend_tx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inputs', to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
