# Generated by Django 4.0.6 on 2022-08-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='blocks.block'),
        ),
        migrations.AlterField(
            model_name='txin',
            name='gen_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='txin',
            name='gen_tx_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='txin',
            name='hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='txin',
            name='spend_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inputs', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='txout',
            name='blk_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='txout',
            name='gen_tx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='outputs', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='txout',
            name='gen_tx_idx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='txout',
            name='hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
