# Generated by Django 4.0.6 on 2022-08-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_block_alter_txin_gen_tx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
