# Generated by Django 4.0.6 on 2022-08-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_alter_block_hash_target_zeros'),
        ('transactions', '0006_alter_transaction_hash_alter_transaction_tx_ins_ct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, editable=False, help_text='hash of the transaction component', max_length=40, null=True)),
                ('value', models.PositiveIntegerField(default=0, help_text='value of the component i.e how much is it worth')),
                ('own_addr', models.CharField(help_text='owner of this component', max_length=100)),
                ('gen_transaction_index', models.PositiveIntegerField(blank=True, help_text='output index in generating transaction', null=True)),
                ('spend_transaction_index', models.PositiveIntegerField(default=0, help_text='input index in spending transaction')),
                ('signature', models.TextField(help_text='digital signature for verification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, editable=False, help_text='hash of the transaction component', max_length=40, null=True)),
                ('value', models.PositiveIntegerField(default=0, help_text='value of the component i.e how much is it worth')),
                ('own_addr', models.CharField(help_text='owner of this component', max_length=100)),
                ('gen_transaction_index', models.PositiveIntegerField(blank=True, help_text='output index in generating transaction', null=True)),
                ('blk_height', models.PositiveIntegerField(blank=True, help_text='height of the block', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='txout',
            name='gen_tx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tx_ins_ct',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tx_outs_ct',
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_inputs_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='number of inputs in the transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_outputs_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='number of outputs in the transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='block',
            field=models.ForeignKey(blank=True, help_text='block this transaction is part of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='blocks.block'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(blank=True, editable=False, help_text='hash of the transaction for identification', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mined',
            field=models.BooleanField(default=False, help_text='has the transaction been mined'),
        ),
        migrations.DeleteModel(
            name='TxIn',
        ),
        migrations.DeleteModel(
            name='TxOut',
        ),
        migrations.AddField(
            model_name='transactionoutput',
            name='gen_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transactioninput',
            name='gen_transaction',
            field=models.ForeignKey(blank=True, help_text='transaction that generated this input', null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transactioninput',
            name='spend_transaction',
            field=models.ForeignKey(blank=True, help_text='transcation that spent this input', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='transactions.transaction'),
        ),
    ]
